# Generated by Django 5.0 on 2024-03-08 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0004_user_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('username', models.CharField(max_length=200)),
                ('email', models.EmailField(max_length=254)),
                ('password', models.CharField(max_length=200)),
                ('age', models.CharField(max_length=200)),
                ('country', models.CharField(max_length=200)),
                ('mobile', models.CharField(max_length=200)),
            ],
            options={
                'db_table': 'Signup',
            },
        ),
        migrations.DeleteModel(
            name='User',
        ),
    ]
