# Generated by Django 5.0 on 2024-03-08 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0006_customuser_delete_signup'),
    ]

    operations = [
        migrations.CreateModel(
            name='Signup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_name', models.CharField(max_length=255)),
                ('email_id', models.CharField(max_length=255)),
                ('password', models.CharField(max_length=255)),
                ('age', models.IntegerField()),
                ('country_name', models.CharField(max_length=255)),
                ('mobile_number', models.CharField(max_length=255)),
            ],
        ),
        migrations.DeleteModel(
            name='CustomUser',
        ),
    ]
